/* generated by generateAst.ts */

import { Token } from "./scanner";

export abstract class ExprVisitor<T> {
   abstract visitAssignExpr(expr: Assign): T
   abstract visitBinaryExpr(expr: Binary): T
   abstract visitCallExpr(expr: Call): T
   abstract visitGroupingExpr(expr: Grouping): T
   abstract visitLiteralExpr(expr: Literal): T
   abstract visitLogicalExpr(expr: Logical): T
   abstract visitUnaryExpr(expr: Unary): T
   abstract visitVariableExpr(expr: Variable): T
}

export abstract class Expr {
  abstract accept(visitor: ExprVisitor<unknown>): unknown;
}

export class Assign extends Expr {
  name: Token
  value: Expr

  constructor (name: Token, value: Expr) {
    super()
    this.name = name
    this.value = value
  }

  accept (visitor: ExprVisitor<unknown>) {
    return visitor.visitAssignExpr(this)
  }
}

export class Binary extends Expr {
  left:Expr
  operator:Token
  right: Expr

  constructor (left:Expr, operator:Token, right: Expr) {
    super()
    this.left = left
    this.operator = operator
    this.right = right
  }

  accept (visitor: ExprVisitor<unknown>) {
    return visitor.visitBinaryExpr(this)
  }
}

export class Call extends Expr {
  callee:Expr
  paren:Token
  args: Expr[]

  constructor (callee:Expr, paren:Token, args: Expr[]) {
    super()
    this.callee = callee
    this.paren = paren
    this.args = args
  }

  accept (visitor: ExprVisitor<unknown>) {
    return visitor.visitCallExpr(this)
  }
}

export class Grouping extends Expr {
  expression:Expr

  constructor (expression:Expr) {
    super()
    this.expression = expression
  }

  accept (visitor: ExprVisitor<unknown>) {
    return visitor.visitGroupingExpr(this)
  }
}

export class Literal extends Expr {
  value: unknown

  constructor (value: unknown) {
    super()
    this.value = value
  }

  accept (visitor: ExprVisitor<unknown>) {
    return visitor.visitLiteralExpr(this)
  }
}

export class Logical extends Expr {
  left:Expr
  operator:Token
  right: Expr

  constructor (left:Expr, operator:Token, right: Expr) {
    super()
    this.left = left
    this.operator = operator
    this.right = right
  }

  accept (visitor: ExprVisitor<unknown>) {
    return visitor.visitLogicalExpr(this)
  }
}

export class Unary extends Expr {
  operator:Token
  right: Expr

  constructor (operator:Token, right: Expr) {
    super()
    this.operator = operator
    this.right = right
  }

  accept (visitor: ExprVisitor<unknown>) {
    return visitor.visitUnaryExpr(this)
  }
}

export class Variable extends Expr {
  name:Token

  constructor (name:Token) {
    super()
    this.name = name
  }

  accept (visitor: ExprVisitor<unknown>) {
    return visitor.visitVariableExpr(this)
  }
}

