/* generated by generateAst.ts */

import { TokenType } from "./scanner";

export abstract class ExprVisitor {
  visitAssignExpr(expr: Assign): void {}
  visitBinaryExpr(expr: Binary): void {}
  visitCallExpr(expr: Call): void {}
  visitGroupingExpr(expr: Grouping): void {}
  visitLiteralExpr(expr: Literal): void {}
  visitLogicalExpr(expr: Logical): void {}
  visitUnaryExpr(expr: Unary): void {}
  visitVariableExpr(expr: Variable): void {}
}

export class Expr {
  accept (visitor: ExprVisitor) {}
}

export class Assign extends Expr {
  name: TokenType
  value: Expr

  constructor (name: TokenType, value: Expr) {
    super()
    this.name = name
    this.value = value
  }

  accept (visitor: ExprVisitor) {
    return visitor.visitAssignExpr(this)
  }
}

export class Binary extends Expr {
  left:Expr
  operator:TokenType
  right: Expr

  constructor (left:Expr, operator:TokenType, right: Expr) {
    super()
    this.left = left
    this.operator = operator
    this.right = right
  }

  accept (visitor: ExprVisitor) {
    return visitor.visitBinaryExpr(this)
  }
}

export class Call extends Expr {
  callee:Expr
  paren:TokenType
  args: Expr[]

  constructor (callee:Expr, paren:TokenType, args: Expr[]) {
    super()
    this.callee = callee
    this.paren = paren
    this.args = args
  }

  accept (visitor: ExprVisitor) {
    return visitor.visitCallExpr(this)
  }
}

export class Grouping extends Expr {
  expression:Expr

  constructor (expression:Expr) {
    super()
    this.expression = expression
  }

  accept (visitor: ExprVisitor) {
    return visitor.visitGroupingExpr(this)
  }
}

export class Literal extends Expr {
  value: unknown

  constructor (value: unknown) {
    super()
    this.value = value
  }

  accept (visitor: ExprVisitor) {
    return visitor.visitLiteralExpr(this)
  }
}

export class Logical extends Expr {
   left:Expr
  operator:TokenType
  right: Expr

  constructor ( left:Expr, operator:TokenType, right: Expr) {
    super()
    this. left =  left
    this.operator = operator
    this.right = right
  }

  accept (visitor: ExprVisitor) {
    return visitor.visitLogicalExpr(this)
  }
}

export class Unary extends Expr {
  operator:TokenType
  right: Expr

  constructor (operator:TokenType, right: Expr) {
    super()
    this.operator = operator
    this.right = right
  }

  accept (visitor: ExprVisitor) {
    return visitor.visitUnaryExpr(this)
  }
}

export class Variable extends Expr {
  name:TokenType

  constructor (name:TokenType) {
    super()
    this.name = name
  }

  accept (visitor: ExprVisitor) {
    return visitor.visitVariableExpr(this)
  }
}

