/* generated by generateAst.ts */

import { Expr } from "./expr";
import { Token } from "./scanner";

export abstract class StmtVisitor<T> {
   abstract visitBlockStmt(expr: Block): T
   abstract visitExpressionStmt(expr: Expression): T
   abstract visitFunctionStmt(expr: Function): T
   abstract visitIfStmt(expr: If): T
   abstract visitPrintStmt(expr: Print): T
   abstract visitReturnStmt(expr: Return): T
   abstract visitVarStmt(expr: Var): T
   abstract visitWhileStmt(expr: While): T
}

export abstract class Stmt {
  abstract accept (visitor: StmtVisitor<unknown>): unknown
}

export class Block extends Stmt {
  statements: Stmt[]

  constructor (statements: Stmt[]) {
    super()
    this.statements = statements
  }

  accept (visitor: StmtVisitor<unknown>) {
    return visitor.visitBlockStmt(this)
  }
}

export class Expression extends Stmt {
  expression: Expr

  constructor (expression: Expr) {
    super()
    this.expression = expression
  }

  accept (visitor: StmtVisitor<unknown>) {
    return visitor.visitExpressionStmt(this)
  }
}

export class Function extends Stmt {
  name:Token
  parameters:Token[]
  body:Stmt[]

  constructor (name:Token, parameters:Token[], body:Stmt[]) {
    super()
    this.name = name
    this.parameters = parameters
    this.body = body
  }

  accept (visitor: StmtVisitor<unknown>) {
    return visitor.visitFunctionStmt(this)
  }
}

export class If extends Stmt {
  condition: Expr
  thenBranch:Stmt
  elseBranch:Stmt | null

  constructor (condition: Expr, thenBranch:Stmt, elseBranch:Stmt | null) {
    super()
    this.condition = condition
    this.thenBranch = thenBranch
    this.elseBranch = elseBranch
  }

  accept (visitor: StmtVisitor<unknown>) {
    return visitor.visitIfStmt(this)
  }
}

export class Print extends Stmt {
  expression: Expr

  constructor (expression: Expr) {
    super()
    this.expression = expression
  }

  accept (visitor: StmtVisitor<unknown>) {
    return visitor.visitPrintStmt(this)
  }
}

export class Return extends Stmt {
  keyword:Token
  value: Expr | null

  constructor (keyword:Token, value: Expr | null) {
    super()
    this.keyword = keyword
    this.value = value
  }

  accept (visitor: StmtVisitor<unknown>) {
    return visitor.visitReturnStmt(this)
  }
}

export class Var extends Stmt {
  name:Token
  initializer: Expr | null

  constructor (name:Token, initializer: Expr | null) {
    super()
    this.name = name
    this.initializer = initializer
  }

  accept (visitor: StmtVisitor<unknown>) {
    return visitor.visitVarStmt(this)
  }
}

export class While extends Stmt {
  condition: Expr
  body:Stmt

  constructor (condition: Expr, body:Stmt) {
    super()
    this.condition = condition
    this.body = body
  }

  accept (visitor: StmtVisitor<unknown>) {
    return visitor.visitWhileStmt(this)
  }
}

