/* generated by generateAst.ts */

import { Expr } from "./Expr";
import { TokenType } from "./scanner";

export abstract class StmtVisitor {
  visitBlockStmt(expr: Block): void {}
  visitExpressionStmt(expr: Expression): void {}
  visitFunctionStmt(expr: Function): void {}
  visitIfStmt(expr: If): void {}
  visitPrintStmt(expr: Print): void {}
  visitReturnStmt(expr: Return): void {}
  visitVarStmt(expr: Var): void {}
  visitWhileStmt(expr: While): void {}
}

export class Stmt {
  accept (visitor: StmtVisitor) {}
}

export class Block extends Stmt {
  statements: Stmt[]

  constructor (statements: Stmt[]) {
    super()
    this.statements = statements
  }

  accept (visitor: StmtVisitor) {
    return visitor.visitBlockStmt(this)
  }
}

export class Expression extends Stmt {
  expression: Expr

  constructor (expression: Expr) {
    super()
    this.expression = expression
  }

  accept (visitor: StmtVisitor) {
    return visitor.visitExpressionStmt(this)
  }
}

export class Function extends Stmt {
  name:TokenType
  parameters:TokenType[]
  body:Stmt[]

  constructor (name:TokenType, parameters:TokenType[], body:Stmt[]) {
    super()
    this.name = name
    this.parameters = parameters
    this.body = body
  }

  accept (visitor: StmtVisitor) {
    return visitor.visitFunctionStmt(this)
  }
}

export class If extends Stmt {
  condition: Expr
  thenBranch:Stmt
  elseBranch:Stmt

  constructor (condition: Expr, thenBranch:Stmt, elseBranch:Stmt) {
    super()
    this.condition = condition
    this.thenBranch = thenBranch
    this.elseBranch = elseBranch
  }

  accept (visitor: StmtVisitor) {
    return visitor.visitIfStmt(this)
  }
}

export class Print extends Stmt {
  expression: Expr

  constructor (expression: Expr) {
    super()
    this.expression = expression
  }

  accept (visitor: StmtVisitor) {
    return visitor.visitPrintStmt(this)
  }
}

export class Return extends Stmt {
  keyword:TokenType
  value: Expr

  constructor (keyword:TokenType, value: Expr) {
    super()
    this.keyword = keyword
    this.value = value
  }

  accept (visitor: StmtVisitor) {
    return visitor.visitReturnStmt(this)
  }
}

export class Var extends Stmt {
  name:TokenType
  initializer: Expr

  constructor (name:TokenType, initializer: Expr) {
    super()
    this.name = name
    this.initializer = initializer
  }

  accept (visitor: StmtVisitor) {
    return visitor.visitVarStmt(this)
  }
}

export class While extends Stmt {
  condition: Expr
  body:Stmt

  constructor (condition: Expr, body:Stmt) {
    super()
    this.condition = condition
    this.body = body
  }

  accept (visitor: StmtVisitor) {
    return visitor.visitWhileStmt(this)
  }
}

