import fs from 'fs';
import path from 'path';

const outputDir = path.resolve(import.meta.filename, '..', '..');

const indent = '  ';

defineAst(outputDir, 'Expr', [['TokenType', './scanner']], {
  Assign: 'name: TokenType, value: Expr',
  Binary: 'left:Expr, operator:TokenType, right: Expr',
  Call: 'callee:Expr, paren:TokenType, args: Expr[]',
  Grouping: 'expression:Expr',
  Literal: 'value: unknown',
  Logical: ' left:Expr, operator:TokenType, right: Expr',
  Unary: 'operator:TokenType, right: Expr',
  Variable: 'name:TokenType'
})

defineAst(outputDir, 'Stmt', [['Expr', './Expr'], ['TokenType', './scanner']], {
  Block: 'statements: Stmt[]',
  Expression: 'expression: Expr',
  Function: 'name:TokenType, parameters:TokenType[], body:Stmt[]',
  If: 'condition: Expr, thenBranch:Stmt, elseBranch:Stmt',
  Print: 'expression: Expr',
  Return: 'keyword:TokenType, value: Expr',
  Var: 'name:TokenType, initializer: Expr',
  While: 'condition: Expr, body:Stmt'
})

function defineAst(outputDir: string, baseName: string, imports: string[][], types: Record<string, string>) {
  const outputPath = path.resolve(outputDir, baseName + '.ts')
  const writer = fs.createWriteStream(outputPath)

  // HEADER
  writer.write(`/* generated by ${path.basename(import.meta.filename)} */\n\n`)

  // IMPORTS
  const allImports = imports.map(([fields, path]) => `import { ${fields} } from "${path}";`).join('\n')
  writer.write(allImports)
  writer.write('\n\n')
  
  // VISITOR INTERFACE
  defineVisitor(writer, baseName, types);

  // BASE CLASS
  writer.write(`export class ${baseName} {\n`);
  writer.write(`${indent}accept (visitor: ${baseName}Visitor) {}\n`);
  writer.write(`}\n\n`);

  // ALL SUB CLASS
  const classNames = Object.keys(types);
  classNames.forEach(className => {
    defineType(writer, baseName, className, types[className]);
    writer.write('\n')
  })


  writer.end()
}

function defineType(writer: fs.WriteStream, baseName: string, className: string, fieldList: string) {
  writer.write(`export class ${className} extends ${baseName} {\n`)

  const fields = fieldList.split(', ')
  const fieldNames = fields.map(field =>
    field.split(':')[0]
  )

  const allThisFields = fields.map(field => `${indent}${field}`).join('\n');
  writer.write(allThisFields);
  writer.write('\n\n');
  writer.write(`${indent}constructor (${fieldList}) {\n`)
  writer.write(`${indent}${indent}super()\n`)
  fieldNames.forEach(fieldName => {
    writer.write(`${indent}${indent}this.${fieldName} = ${fieldName}\n`)
  })
  writer.write(`${indent}}\n\n`)

  writer.write(`${indent}accept (visitor: ${baseName}Visitor) {\n`)
  writer.write(`${indent}${indent}return visitor.visit${className}${baseName}(this)\n`)
  writer.write(`${indent}}\n`)

  writer.write(`}\n`)
}

function defineVisitor(writer: fs.WriteStream, baseName: string, types: Record<string, string>) {
  writer.write(`export abstract class ${baseName}Visitor {\n`);
  const classNames = Object.keys(types);
  const classNameMethods = classNames.map(className => 
    `${indent}visit${className}${baseName}(expr: ${className}): void {}`
  ).join('\n');
  writer.write(classNameMethods);
  writer.write(`\n}\n\n`);
}