import fs from 'fs';
import path from 'path';

const outputDir = path.resolve(import.meta.filename, '..', '..');

const indent = '  ';

defineAst(outputDir, 'Expr', [['Token', './scanner']], {
  Assign: 'name: Token, value: Expr',
  Binary: 'left:Expr, operator:Token, right: Expr',
  Call: 'callee:Expr, paren:Token, args: Expr[]',
  Grouping: 'expression:Expr',
  Literal: 'value: unknown',
  Logical: 'left:Expr, operator:Token, right: Expr',
  Unary: 'operator:Token, right: Expr',
  Variable: 'name:Token'
})

defineAst(outputDir, 'Stmt', [['Expr', './expr'], ['Token', './scanner']], {
  Block: 'statements: Stmt[]',
  Expression: 'expression: Expr',
  Function: 'name:Token, parameters:Token[], body:Stmt[]',
  If: 'condition: Expr, thenBranch:Stmt, elseBranch:Stmt',
  Print: 'expression: Expr',
  Return: 'keyword:Token, value: Expr',
  Var: 'name:Token, initializer: Expr | null',
  While: 'condition: Expr, body:Stmt'
})

function defineAst(outputDir: string, baseName: string, imports: string[][], types: Record<string, string>) {
  const outputPath = path.resolve(outputDir, baseName.toLowerCase() + '.ts')
  const writer = fs.createWriteStream(outputPath)

  // HEADER
  writer.write(`/* generated by ${path.basename(import.meta.filename)} */\n\n`)

  // IMPORTS
  const allImports = imports.map(([fields, path]) => `import { ${fields} } from "${path}";`).join('\n')
  writer.write(allImports)
  writer.write('\n\n')
  
  // VISITOR INTERFACE
  defineVisitor(writer, baseName, types);

  // BASE CLASS
  writer.write(`export abstract class ${baseName} {\n`);
  writer.write(`${indent}abstract accept (visitor: ${baseName}Visitor<unknown>): unknown\n`);
  writer.write(`}\n\n`);

  // ALL SUB CLASS
  const classNames = Object.keys(types);
  classNames.forEach(className => {
    defineType(writer, baseName, className, types[className]);
    writer.write('\n')
  })


  writer.end()
}

function defineType(writer: fs.WriteStream, baseName: string, className: string, fieldList: string) {
  writer.write(`export class ${className} extends ${baseName} {\n`)

  const fields = fieldList.split(', ')
  const fieldNames = fields.map(field =>
    field.split(':')[0]
  )

  const allThisFields = fields.map(field => `${indent}${field}`).join('\n');
  writer.write(allThisFields);
  writer.write('\n\n');
  writer.write(`${indent}constructor (${fieldList}) {\n`)
  writer.write(`${indent}${indent}super()\n`)
  fieldNames.forEach(fieldName => {
    writer.write(`${indent}${indent}this.${fieldName} = ${fieldName}\n`)
  })
  writer.write(`${indent}}\n\n`)

  writer.write(`${indent}accept (visitor: ${baseName}Visitor<unknown>) {\n`)
  writer.write(`${indent}${indent}return visitor.visit${className}${baseName}(this)\n`)
  writer.write(`${indent}}\n`)

  writer.write(`}\n`)
}

function defineVisitor(writer: fs.WriteStream, baseName: string, types: Record<string, string>) {
  writer.write(`export abstract class ${baseName}Visitor<T> {\n`);
  const classNames = Object.keys(types);
  const classNameMethods = classNames.map(className => 
    `${indent} abstract visit${className}${baseName}(expr: ${className}): T`
  ).join('\n');
  writer.write(classNameMethods);
  writer.write(`\n}\n\n`);
}